name: CI

on:
  push: ~
  pull_request:
    branches:
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: php-actions/composer@v1
      - uses: php-actions/phpunit@v1